version: '3.8'

services:
  # Extractor Service (Backend)
  extractor:
    build:
      context: ./services/extractor
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=extractor
      - SERVICE_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./shared:/app/shared
      - ./examples:/app/examples
    networks:
      - oersync-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service (Vite React App)
  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - extractor
    networks:
      - oersync-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  oersync-network:
    driver: bridge
